name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    uses: ./.github/workflows/reusable-release.yml
    with:
      release_tag: ${{ github.ref_name }}
      git_ref: ${{ github.ref }}
    secrets: inherit
